-- YouthSync Phase 2 — Youth Management
-- Non-destructive. Does not drop the database or Phase 1 tables.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS youth (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id INT UNSIGNED NOT NULL,
  code VARCHAR(20) NOT NULL,
  first_name VARCHAR(80) NOT NULL,
  middle_name VARCHAR(80) NOT NULL DEFAULT '',
  last_name VARCHAR(80) NOT NULL,
  birth_date DATE NOT NULL,
  gender VARCHAR(32) NOT NULL DEFAULT 'Prefer not to say',
  address VARCHAR(255) NOT NULL,
  contact VARCHAR(20) NOT NULL DEFAULT '',
  email VARCHAR(190) NULL DEFAULT NULL,
  civil_status VARCHAR(32) NOT NULL DEFAULT 'Single',
  education_status VARCHAR(64) NOT NULL DEFAULT 'Not Currently Studying',
  education VARCHAR(64) NOT NULL DEFAULT 'Senior High School',
  school VARCHAR(160) NOT NULL DEFAULT '',
  course VARCHAR(160) NOT NULL DEFAULT '',
  year_level VARCHAR(64) NOT NULL DEFAULT '',
  strand VARCHAR(64) NOT NULL DEFAULT '',
  studying TINYINT(1) NOT NULL DEFAULT 0,
  employment VARCHAR(32) NOT NULL DEFAULT 'Unemployed',
  occupation VARCHAR(120) NOT NULL DEFAULT '',
  guardian_name VARCHAR(160) NOT NULL DEFAULT '',
  guardian_employment VARCHAR(32) NULL DEFAULT NULL,
  guardian_occupation VARCHAR(120) NOT NULL DEFAULT '',
  family_income DECIMAL(12,2) NOT NULL DEFAULT 0,
  family_members INT UNSIGNED NOT NULL DEFAULT 0,
  skills JSON NULL,
  interests JSON NULL,
  preferred_activities JSON NULL,
  previous_scholarship TINYINT(1) NOT NULL DEFAULT 0,
  previous_assistance TINYINT(1) NOT NULL DEFAULT 0,
  previous_participation TINYINT(1) NOT NULL DEFAULT 0,
  archived TINYINT(1) NOT NULL DEFAULT 0,
  self_registered TINYINT(1) NOT NULL DEFAULT 0,
  priority_level VARCHAR(16) NOT NULL DEFAULT 'Medium',
  priority_score INT NOT NULL DEFAULT 0,
  priority_reasons JSON NULL,
  added_at DATETIME NULL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_youth_org_code (organization_id, code),
  KEY idx_youth_org_archived (organization_id, archived),
  KEY idx_youth_org_created (organization_id, created_at),
  KEY idx_youth_org_name_birth (organization_id, last_name, first_name, birth_date),
  KEY idx_youth_priority (organization_id, priority_level),
  KEY idx_youth_employment (organization_id, employment),
  CONSTRAINT fk_youth_organization FOREIGN KEY (organization_id)
    REFERENCES organizations (id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
